### ISSUE TITLE
Does this need Matlab Database Toolbox?

### ISSUE THREAD

**Issue by jankap** [mathworks-ref-arch/matlab-aws-athena#2]
This repo look very promising, however I do not have the Database TB. Is it required to run this package? If not, is vanilla Matlab 2021a sufficient?

Thanks!

**Comment by brownemi** [comment]
Hi jankap

MATLAB 2021a is sufficient to use this package. Database Toolbox is not required. You will however need Maven and a JDK as per the requirements in the README to build a required jar file.

**Comment by jankap** [comment]
Awesome, thank you! Is this the recommended way to communicate with AWS in a production setting?

**Comment by brownemi** [comment]
For Athena, yes, this is the recommended approach. For other AWS services different approaches would apply.
