### ISSUE TITLE
Athena over proxy

### ISSUE THREAD

**Issue by roslovets** [mathworks-ref-arch/matlab-aws-athena#3]
How is it posible to make Athena Client work over proxy? MATLAB network settings don't help.
Thank you.

**Comment by asollander** [comment]
Thanks for the question.

The current release doesn't support Athena access via a proxy. We're investigating how best to add this functionality.

**Comment by roslovets** [comment]
Thank you for response. I added proxy into `initialize.m` using `ApacheHttpClient` and `ProxyConfiguration` and it works.
Awaiting for official support.

**Comment by asollander** [comment]
We now have an updated version, 0.2.4., with proxy support
