### ISSUE TITLE
Stop Query Feature?

### ISSUE THREAD

**Issue by NewGuy012** [mathworks-ref-arch/matlab-aws-athena#4]
Hello, first of all, thank you for this tool. Currently the interface allows for submitting a query but not stopping a query. Would it be possible to add the ability to stop a query as well?

**Comment by asollander** [comment]
Hi,

we'll look into this and get back to you.

Thanks!

**Comment by asollander** [comment]
The latest release of 0.2.4 contains the `stopQueryExecution` method.
